### ISSUE TITLE
Bounty is Funded 3 Times in Row

### ISSUE THREAD

**Issue by andytudhope** [status-im/autobounty#10]
Keep track of the last 10 GHI ids and do not send funds to already-funded bounties. If people really want to add additional funds, they can always just restart the service.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 638.69
Contract address: [0x5c7618ad221117890d90ea91105575b1066eac57](https://etherscan.io/address/0x5c7618ad221117890d90ea91105575b1066eac57)
Network: Mainnet
Paid to: PombeirP
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
